include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Clean code
    avoid_print: true
    avoid_unnecessary_containers: true


    # Performance
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true

    # Readability
    always_declare_return_types: true
    sort_child_properties_last: true
    lines_longer_than_80_chars: false

    # Best practice
    avoid_empty_else: true
    avoid_init_to_null: true

    # Flutter specific
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
