// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOMomQG-p6r1LBXIaxoESStWlhtlzuevE',
    appId: '1:417887773:web:49a9503737c971ad20b8f4',
    messagingSenderId: '417887773',
    projectId: 'lecturefirebase-7945c',
    authDomain: 'lecturefirebase-7945c.firebaseapp.com',
    storageBucket: 'lecturefirebase-7945c.firebasestorage.app',
    measurementId: 'G-YP23WNCBSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClrDYN4gKrWMtqjux2Zhhy4BW_bIraUUQ',
    appId: '1:417887773:android:05663b0bf014d07620b8f4',
    messagingSenderId: '417887773',
    projectId: 'lecturefirebase-7945c',
    storageBucket: 'lecturefirebase-7945c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CVCqKvBQNujM4x93PxOmkkCaRDAokKg',
    appId: '1:417887773:ios:69d8be2a645edc3320b8f4',
    messagingSenderId: '417887773',
    projectId: 'lecturefirebase-7945c',
    storageBucket: 'lecturefirebase-7945c.firebasestorage.app',
    androidClientId:
        '417887773-c8p3e2mtbjri24v9cb9lriuttdvtb239.apps.googleusercontent.com',
    iosClientId:
        '417887773-i20am4hu3a03hgstcdf3jk6p89aefr8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.almasry2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CVCqKvBQNujM4x93PxOmkkCaRDAokKg',
    appId: '1:417887773:ios:69d8be2a645edc3320b8f4',
    messagingSenderId: '417887773',
    projectId: 'lecturefirebase-7945c',
    storageBucket: 'lecturefirebase-7945c.firebasestorage.app',
    androidClientId:
        '417887773-c8p3e2mtbjri24v9cb9lriuttdvtb239.apps.googleusercontent.com',
    iosClientId:
        '417887773-i20am4hu3a03hgstcdf3jk6p89aefr8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.almasry2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOMomQG-p6r1LBXIaxoESStWlhtlzuevE',
    appId: '1:417887773:web:131f8fa6685f860a20b8f4',
    messagingSenderId: '417887773',
    projectId: 'lecturefirebase-7945c',
    authDomain: 'lecturefirebase-7945c.firebaseapp.com',
    storageBucket: 'lecturefirebase-7945c.firebasestorage.app',
    measurementId: 'G-W595VGQ1NB',
  );
}
