library;

import 'package:easy_localization/easy_localization.dart';
import 'package:almasry_2/core/localization/locale_keys.dart';
import 'package:almasry_2/core/base/bloc/generic_cubit.dart';
import 'package:almasry_2/core/base/bloc/generic_state.dart';
import 'package:almasry_2/core/base/locator/locator.dart';
import 'package:almasry_2/core/models/request/product_list_request/product_list_model.dart';
import 'package:almasry_2/core/models/response/product_details/product_details_args_model.dart';
import 'package:almasry_2/core/models/response/product_list/product_model.dart';
import 'package:almasry_2/core/models/response/product_list/product_list_model.dart';
import 'package:almasry_2/core/routing/app_routes.dart';
import 'package:almasry_2/core/services/api_services.dart';
import 'package:almasry_2/core/services/navigation_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:almasry_2/core/constants/app_colors.dart';
import 'package:almasry_2/core/widgets/custom_app_card.dart';
import 'package:almasry_2/core/widgets/custom_app_discount_banner.dart';
import 'package:almasry_2/core/widgets/custom_app_error_view.dart';
import 'package:almasry_2/core/widgets/custom_app_empty_view.dart';
import 'package:almasry_2/core/widgets/custom_app_favorite_button.dart';
import 'package:almasry_2/core/widgets/custom_app_loading_view.dart';
import 'package:almasry_2/core/widgets/custom_app_network_image.dart';
import 'package:almasry_2/core/widgets/custom_app_price_row.dart';
import 'package:almasry_2/core/widgets/custom_app_quantity_stepper.dart';
import 'package:almasry_2/core/widgets/custom_app_status_banner.dart';
import 'package:almasry_2/core/widgets/custom_app_title_app_bar.dart';
import 'package:almasry_2/core/utils/error_message.dart';

part 'view/product_list_view.dart';
part 'widgets/product_list_body.dart';
part 'widgets/product_list_item.dart';
part 'view_model/product_list_view_model.dart';
